### ISSUE TITLE
how to setup fitcrack with SSL ?

### ISSUE THREAD

**Issue by CryptoCoinLab** [nesfit/fitcrack#16] opened 2021-03-18 01:58 UTC
We setup fitcrack to test.
how to setup fitcrack with SSL ?

BTW, we got the message as following always when visit installed fitcrack 

The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by ihranicky** [comment] 2021-12-09 11:35
Hello, nice to hear that you are interested in our system.

The problem is due to the updates in web browsers that changed the security policies. They currently discard all non-HTTPS cookies except the localhost.

However, just for testing, you can use Fitcrack without SSL. There are two options:
1) Install it locally on the 127.0.0.1, connect from local computer
2) Try the development version from the master-next branch:
https://github.com/nesfit/fitcrack/tree/master-next
which supports an alternative authentication for testing purposes that works without SSL

Please, let us know if that works for you.

___

If you use the development version and later decide set to set up SSL and switch to the original (and more secure) cookie-based authentication, just check:
fitcrackAPI/src/settings.py
# Webadmin security
ALLOW_TOKEN_SIGNIN = True # Disable this for installations exposed to the internet!!!
And change this to False.

Setting up SSL requires to enable mod_ssl, import a certificate to the Apache web server on the server and configure it for all the sites. This currently needs to be done manually, as the certificate is typically assigned to a concrete domain. You can use Letsencrypt or other solution, but the setup is a bit complex and meant for deployment. We consider making a how-to in the future.

**Comment by davidbolvansky** [comment] 2022-08-14 17:11
Available now in dev brach (soon big release): https://github.com/nesfit/fitcrack/blob/dev/INSTALL-Docker.md

**Closed by davidbolvansky** 2022-08-14 17:11 UTC
