### ISSUE TITLE
API Server Unreachable : 5000 Error for WebAdmin

### ISSUE THREAD

**Issue by staxmood** [nesfit/fitcrack#70] opened 2023-03-07 03:13 UTC
Looking for general thoughts on where to look next. I've tried installing fircrack over a few different methods and all are coming up to this error.

I've tried the docker version and the installer version on ubuntu server 20 and 22 but all come to the same error. Because at this point i am just trying to get the service up and running, i have changed no defaults within the .env and left with localhost and same for the installer version. No errors when going through the build phase or the installation. When jumping onto the webpage "http://localhost/login" I get the error about the API not being available. When trying to debug via docker instructions, i can confirm that an error page is present on the 5000 port "internal server error" rather than something working. I'm including some of the log snippets here from the apache log that may be relevant.

Also checked service. Fitcrack was inactive when checked but when brought up to be active but no change in behavior of the WebAdmin on 5000.

`[Mon Mar 06 20:57:27.872708 2023] [core:notice] [pid 23491] AH00094: Command line: '/usr/sbin/apache2'
[Mon Mar 06 20:58:05.931414 2023] [mpm_prefork:notice] [pid 23491] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Mar 06 20:58:06.106869 2023] [mpm_prefork:notice] [pid 23627] AH00163: Apache/2.4.52 (Ubuntu) mod_wsgi/4.9.0 Python/3.10 configured -- resuming normal operations
[Mon Mar 06 20:58:06.106936 2023] [core:notice] [pid 23627] AH00094: Command line: '/usr/sbin/apache2'
[Mon Mar 06 20:58:39.051592 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150] mod_wsgi (pid=23628): Failed to exec Python script file '/var/www/html/fitcrackAPI/src/wsgi.py'.
[Mon Mar 06 20:58:39.052016 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150] mod_wsgi (pid=23628): Exception occurred processing WSGI script '/var/www/html/fitcrackAPI/src/wsgi.py'.
[Mon Mar 06 20:58:39.053251 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150] Traceback (most recent call last):
[Mon Mar 06 20:58:39.053295 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]   File "/var/www/html/fitcrackAPI/src/wsgi.py", line 12, in <module>
[Mon Mar 06 20:58:39.053303 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]     from app import app as application
[Mon Mar 06 20:58:39.053310 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]   File "/var/www/html/fitcrackAPI/src/app.py", line 16, in <module>
[Mon Mar 06 20:58:39.053315 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]     from src.api.fitcrack.endpoints.chart.chart import ns as chart_namespace
[Mon Mar 06 20:58:39.053322 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]   File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/chart/chart.py", line 13, in <module>
[Mon Mar 06 20:58:39.053328 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]     from src.database import db
[Mon Mar 06 20:58:39.053334 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]   File "/var/www/html/fitcrackAPI/src/src/database/__init__.py", line 8, in <module>
[Mon Mar 06 20:58:39.053340 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]     db = SQLAlchemy()
[Mon Mar 06 20:58:39.053346 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]   File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py", line 754, in __init__
[Mon Mar 06 20:58:39.053352 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]     _include_sqlalchemy(self, query_class)
[Mon Mar 06 20:58:39.053371 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]   File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py", line 108, in _include_sqlalchemy
[Mon Mar 06 20:58:39.053377 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150]     for key in module.__all__:
[Mon Mar 06 20:58:39.053392 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:47150] AttributeError: module 'sqlalchemy' has no attribute '__all__'
[Mon Mar 06 20:58:41.082267 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:60056] mod_wsgi (pid=23628): Failed to exec Python script file '/var/www/html/fitcrackAPI/src/wsgi.py'.
[Mon Mar 06 20:58:41.082367 2023] [wsgi:error] [pid 23628] [remote 127.0.0.1:60056] mod_wsgi (pid=23628): Exception occurred processing WSGI script '/var/www/html/fitcrackAPI/src/wsgi.py'.` 

<img width="714" alt="image" src="https://user-images.githubusercontent.com/55040826/223308960-d411104c-18e9-409d-988b-f229a3b16c92.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/55040826/223309694-ea9526f4-3683-4ea4-8f30-e0078f000268.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/55040826/223309991-0b563815-7e46-4de7-8d0d-2fa49efb052b.png">

**Comment by staxmood** [comment] 2023-03-07 04:54
Can confirm that the docker engine was version 20.10.13 and the compose was 1.29.2. When installing docker engine, a new version of compose was installed. This was removed and 1.29.2 was brought in with same error. This has all also been attempted with up to date version of engine and compose.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/55040826/223316266-a328cd05-dab5-4b1e-bef8-dce2c56bdce0.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/55040826/223317187-856c8f7f-dc30-4cf0-ac9d-5f372d344b10.png">

**Comment by ihranicky** [comment] 2023-03-14 13:37
Seems to be duplicate of #64

**Closed by ihranicky** 2023-03-14 13:37 UTC
