### ISSUE TITLE
webadmin backend fail to work with 500 error.

### ISSUE THREAD

**Issue by hueta** [nesfit/fitcrack#64] opened 2023-02-01 13:48 UTC
Hi. When installing fitcrack on ubuntu 20 with dockerm fitcrack fails to start backend, giving 500 apache error when trying to access port

backend error log:

 [wsgi:error]  mod_wsgi (pid=687): Failed to exec Python script file '/var/www/html/fitcrackAPI/src/wsgi.py'.
 [wsgi:error]  mod_wsgi (pid=687): Exception occurred processing WSGI script '/var/www/html/fitcrackAPI/src/wsgi.py'.
 [wsgi:error]  Traceback (most recent call last):
 [wsgi:error]    File "/var/www/html/fitcrackAPI/src/wsgi.py", line 12, in <module>
 [wsgi:error]      from app import app as application
 [wsgi:error]    File "/var/www/html/fitcrackAPI/src/app.py", line 16, in <module>
 [wsgi:error]      from src.api.fitcrack.endpoints.chart.chart import ns as chart_namespace
 [wsgi:error]    File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/endpoints/chart/chart.py", line 13, in <module>
 [wsgi:error]      from src.database import db
 [wsgi:error]    File "/var/www/html/fitcrackAPI/src/src/database/__init__.py", line 8, in <module>
 [wsgi:error]      db = SQLAlchemy()
 [wsgi:error]    File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py", line 754, in __init__
 [wsgi:error]      _include_sqlalchemy(self, query_class)
 [wsgi:error]    File "/usr/local/lib/python3.10/dist-packages/flask_sqlalchemy/__init__.py", line 108, in _include_sqlalchemy
 [wsgi:error]      for key in module.__all__:
 [wsgi:error]  AttributeError: module 'sqlalchemy' has no attribute '__all__'

**Comment by ermolushka** [comment] 2023-02-05 20:08
Same here. Weird, sqlalchemy version seem to be fixed in requirements.

**Comment by ermolushka** [comment] 2023-02-05 21:40
Most probably recent release broke it https://pypi.org/project/SQLAlchemy/2.0.1/#history

**Comment by Phikzel2** [comment] 2023-02-15 11:27
Same issue here. Ubuntu 22.04 and 20.04. Both with Docker and Installer.

Using Flask-SQLAlchemy v3.0.3 instead of 2.5.0 fixes this specific error, but breaks other crucial stuff. Can't get this to work.

**Comment by crecos** [comment] 2023-02-25 02:08
Mám stejný problém. Na ubuntu 22.04 nelze zprovoznit jak instalací tak ani v dockeru

**Comment by ihranicky** [comment] 2023-03-14 13:37
Please try the last version from "dev" branch. The issue was probably caused by using an incorrect version of Python sqlalchemy module. Let us know it that helped.

**Comment by staxmood** [comment] 2023-03-16 03:03
Can confirm that #70 was a duplicate of #64. After testing, I can confirm that the dev commit [f2a0232](https://github.com/nesfit/fitcrack/commit/f2a0232dd77ef7b4a0ff1fceb736b3d8f169a057) of adding sqlalchemy==1.4.46 to the API requirements file did fix the issue on my testing platforms of docker on ubuntu and installer on ubuntu server 22.

**Comment by Phikzel2** [comment] 2023-03-16 08:40
Hello, I tried this with the latest version from "dev" branch, and it works! Installed on Ubuntu 20.04 LTS with the Installer. Thanks!

**Closed** 2023-04-07 15:09 UTC
